management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
resilience4j:
  bulkhead:
    instances:
      bulkheadApi:
        max-concurrent-calls: 3
        max-wait-duration: 1
    metrics:
      enabled: true
  circuitbreaker:
    instances:
      CircuitBreakerService:
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count_based
        wait-duration-in-open-state: 5s
  ratelimiter:
    instances:
      rateLimiterApi:
        allow-health-indicator-to-fail: true
        event-consumer-buffer-size: 50
        limit-for-period: 5
        limit-refresh-period: 60s
        register-health-indicator: true
        subscribe-for-events: true
        timeout-duration: 0s
    metrics:
      enabled: true
  retry:
    instances:
      retryApi:
        max-attempts: 3
        wait-duration: 1s
    metrics:
      enabled: true
      legacy:
        enabled: true
  timelimiter:
    instances:
      timeLimiterApi:
        cancel-running-future: true
        timeout-duration: 2s
    metrics:
      enabled: true
spring:
  application:
    name: resiliencyTest
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka